spring:
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: postgres

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

library:
  endpoint: http://localhost:8090
  username: libuser
  password: libpass
  connectionTimeout: 30
  readWriteTimeout: 30
